/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Colas.Factory;

/**
 *
 * @author edugonch
 */
public enum Factories {
    CAMINO_PRINCIPAL,
    //VENDEDORES
    CAMINO_HACIA_VENDEDORES,
    CAMINO_HACIA_VENDEDORES1,
    CAMINO_HACIA_VENDEDORES2,
    CAMINO_HACIA_VENDEDORES3,
    CAMINO_HACIA_VENDEDORES4,
    CAMINO_HACIA_VENDEDORES5,
    CAMINO_HACIA_VENDEDORES6,
    CAMINO_DESDE_VENDEDORES1,
    CAMINO_DESDE_VENDEDORES2,
    CAMINO_DESDE_VENDEDORES3,
    CAMINO_DESDE_VENDEDORES4,
    CAMINO_DESDE_VENDEDORES5,
    CAMINO_DESDE_VENDEDORES6,
    // ------------
    // CAJAS
    CAMINO_HACIA_CAJAS,
    CAMINO_HACIA_CAJAS1,
    CAMINO_HACIA_CAJAS2,
    CAMINO_HACIA_CAJAS3,
    CAMINO_HACIA_CAJAS4,
    CAMINO_HACIA_CAJAS5,
    CAMINO_HACIA_CAJAS6,
    CAMINO_DESDE_CAJAS1,
    CAMINO_DESDE_CAJAS2,
    CAMINO_DESDE_CAJAS3,
    CAMINO_DESDE_CAJAS4,
    CAMINO_DESDE_CAJAS5,
    CAMINO_DESDE_CAJAS6,
    // -------------
    // BODEGUEROS
    CAMINO_HACIA_BODEGUEROS,
    CAMINO_HACIA_BODEGUEROS1,
    CAMINO_HACIA_BODEGUEROS2,
    CAMINO_HACIA_BODEGUEROS3,
    CAMINO_HACIA_BODEGUEROS4,
    CAMINO_HACIA_BODEGUEROS5,
    // -------------
    // BODEGAS
    CAMINO_HACIA_BODEGA1,
    CAMINO_HACIA_BODEGA2,
    CAMINO_HACIA_BODEGA3,
    CAMINO_HACIA_BODEGA4,
    CAMINO_HACIA_BODEGA5,
}
