/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * NewJPanel.java
 *
 * Created on Aug 19, 2011, 10:43:28 AM
 */
package proyecto_final_io;

/**
 *
 * @author eduardo
 */
public class PanelOpciones extends javax.swing.JPanel {

    
    /** Creates new form NewJPanel */
    public PanelOpciones() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        chkVendedores1 = new javax.swing.JCheckBox();
        chkVendores2 = new javax.swing.JCheckBox();
        chkVendedores3 = new javax.swing.JCheckBox();
        chkVendedores4 = new javax.swing.JCheckBox();
        chkVendedores5 = new javax.swing.JCheckBox();
        chkVendedores6 = new javax.swing.JCheckBox();
        jPanel2 = new javax.swing.JPanel();
        chkCajeros1 = new javax.swing.JCheckBox();
        chkCajeros2 = new javax.swing.JCheckBox();
        chkCajeros3 = new javax.swing.JCheckBox();
        chkCajeros4 = new javax.swing.JCheckBox();
        chkCajeros5 = new javax.swing.JCheckBox();
        chkCajeros6 = new javax.swing.JCheckBox();
        jPanel3 = new javax.swing.JPanel();
        chkBodeguero1 = new javax.swing.JCheckBox();
        chkBodeguero2 = new javax.swing.JCheckBox();
        chkBodeguero3 = new javax.swing.JCheckBox();
        chkBodeguero4 = new javax.swing.JCheckBox();
        chkBodeguero5 = new javax.swing.JCheckBox();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();

        setName("Form"); // NOI18N
        setLayout(new java.awt.GridLayout(4, 1));

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(proyecto_final_io.Proyecto_Final_IOApp.class).getContext().getResourceMap(PanelOpciones.class);
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(resourceMap.getString("jPanel1.border.title"))); // NOI18N
        jPanel1.setName("jPanel1"); // NOI18N
        jPanel1.setLayout(new java.awt.GridLayout(2, 3));

        chkVendedores1.setText(resourceMap.getString("chkVendedores1.text")); // NOI18N
        chkVendedores1.setName("chkVendedores1"); // NOI18N
        jPanel1.add(chkVendedores1);

        chkVendores2.setText(resourceMap.getString("chkVendores2.text")); // NOI18N
        chkVendores2.setName("chkVendores2"); // NOI18N
        jPanel1.add(chkVendores2);

        chkVendedores3.setText(resourceMap.getString("chkVendedores3.text")); // NOI18N
        chkVendedores3.setName("chkVendedores3"); // NOI18N
        jPanel1.add(chkVendedores3);

        chkVendedores4.setText(resourceMap.getString("chkVendedores4.text")); // NOI18N
        chkVendedores4.setName("chkVendedores4"); // NOI18N
        jPanel1.add(chkVendedores4);

        chkVendedores5.setText(resourceMap.getString("chkVendedores5.text")); // NOI18N
        chkVendedores5.setName("chkVendedores5"); // NOI18N
        jPanel1.add(chkVendedores5);

        chkVendedores6.setText(resourceMap.getString("chkVendedores6.text")); // NOI18N
        chkVendedores6.setName("chkVendedores6"); // NOI18N
        jPanel1.add(chkVendedores6);

        add(jPanel1);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(resourceMap.getString("jPanel2.border.title"))); // NOI18N
        jPanel2.setName("jPanel2"); // NOI18N
        jPanel2.setLayout(new java.awt.GridLayout(2, 3));

        chkCajeros1.setText(resourceMap.getString("chkCajeros1.text")); // NOI18N
        chkCajeros1.setName("chkCajeros1"); // NOI18N
        jPanel2.add(chkCajeros1);

        chkCajeros2.setText(resourceMap.getString("chkCajeros2.text")); // NOI18N
        chkCajeros2.setName("chkCajeros2"); // NOI18N
        jPanel2.add(chkCajeros2);

        chkCajeros3.setText(resourceMap.getString("chkCajeros3.text")); // NOI18N
        chkCajeros3.setName("chkCajeros3"); // NOI18N
        jPanel2.add(chkCajeros3);

        chkCajeros4.setText(resourceMap.getString("chkCajeros4.text")); // NOI18N
        chkCajeros4.setName("chkCajeros4"); // NOI18N
        jPanel2.add(chkCajeros4);

        chkCajeros5.setText(resourceMap.getString("chkCajeros5.text")); // NOI18N
        chkCajeros5.setName("chkCajeros5"); // NOI18N
        jPanel2.add(chkCajeros5);

        chkCajeros6.setText(resourceMap.getString("chkCajeros6.text")); // NOI18N
        chkCajeros6.setName("chkCajeros6"); // NOI18N
        jPanel2.add(chkCajeros6);

        add(jPanel2);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(resourceMap.getString("jPanel3.border.title"))); // NOI18N
        jPanel3.setName("jPanel3"); // NOI18N
        jPanel3.setLayout(new java.awt.GridLayout(2, 3));

        chkBodeguero1.setText(resourceMap.getString("chkBodeguero1.text")); // NOI18N
        chkBodeguero1.setName("chkBodeguero1"); // NOI18N
        jPanel3.add(chkBodeguero1);

        chkBodeguero2.setText(resourceMap.getString("chkBodeguero2.text")); // NOI18N
        chkBodeguero2.setName("chkBodeguero2"); // NOI18N
        jPanel3.add(chkBodeguero2);

        chkBodeguero3.setText(resourceMap.getString("chkBodeguero3.text")); // NOI18N
        chkBodeguero3.setName("chkBodeguero3"); // NOI18N
        jPanel3.add(chkBodeguero3);

        chkBodeguero4.setText(resourceMap.getString("chkBodeguero4.text")); // NOI18N
        chkBodeguero4.setName("chkBodeguero4"); // NOI18N
        jPanel3.add(chkBodeguero4);

        chkBodeguero5.setText(resourceMap.getString("chkBodeguero5.text")); // NOI18N
        chkBodeguero5.setName("chkBodeguero5"); // NOI18N
        jPanel3.add(chkBodeguero5);

        add(jPanel3);

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(resourceMap.getString("jPanel4.border.title"))); // NOI18N
        jPanel4.setName("jPanel4"); // NOI18N
        jPanel4.setLayout(new java.awt.GridLayout(0, 4, 10, 5));

        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N
        jPanel4.add(jLabel1);

        jTextField1.setText(resourceMap.getString("jTextField1.text")); // NOI18N
        jTextField1.setName("jTextField1"); // NOI18N
        jPanel4.add(jTextField1);

        jLabel2.setText(resourceMap.getString("jLabel2.text")); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N
        jPanel4.add(jLabel2);

        jTextField2.setText(resourceMap.getString("jTextField2.text")); // NOI18N
        jTextField2.setName("jTextField2"); // NOI18N
        jPanel4.add(jTextField2);

        jLabel6.setText(resourceMap.getString("jLabel6.text")); // NOI18N
        jLabel6.setName("jLabel6"); // NOI18N
        jPanel4.add(jLabel6);

        jTextField6.setText(resourceMap.getString("jTextField6.text")); // NOI18N
        jTextField6.setName("jTextField6"); // NOI18N
        jPanel4.add(jTextField6);

        jLabel3.setText(resourceMap.getString("jLabel3.text")); // NOI18N
        jLabel3.setName("jLabel3"); // NOI18N
        jPanel4.add(jLabel3);

        jTextField3.setText(resourceMap.getString("jTextField3.text")); // NOI18N
        jTextField3.setName("jTextField3"); // NOI18N
        jPanel4.add(jTextField3);

        jLabel4.setText(resourceMap.getString("jLabel4.text")); // NOI18N
        jLabel4.setName("jLabel4"); // NOI18N
        jPanel4.add(jLabel4);

        jTextField4.setText(resourceMap.getString("jTextField4.text")); // NOI18N
        jTextField4.setName("jTextField4"); // NOI18N
        jPanel4.add(jTextField4);

        jLabel5.setText(resourceMap.getString("jLabel5.text")); // NOI18N
        jLabel5.setName("jLabel5"); // NOI18N
        jPanel4.add(jLabel5);

        jTextField5.setText(resourceMap.getString("jTextField5.text")); // NOI18N
        jTextField5.setName("jTextField5"); // NOI18N
        jPanel4.add(jTextField5);

        add(jPanel4);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox chkBodeguero1;
    private javax.swing.JCheckBox chkBodeguero2;
    private javax.swing.JCheckBox chkBodeguero3;
    private javax.swing.JCheckBox chkBodeguero4;
    private javax.swing.JCheckBox chkBodeguero5;
    private javax.swing.JCheckBox chkCajeros1;
    private javax.swing.JCheckBox chkCajeros2;
    private javax.swing.JCheckBox chkCajeros3;
    private javax.swing.JCheckBox chkCajeros4;
    private javax.swing.JCheckBox chkCajeros5;
    private javax.swing.JCheckBox chkCajeros6;
    private javax.swing.JCheckBox chkVendedores1;
    private javax.swing.JCheckBox chkVendedores3;
    private javax.swing.JCheckBox chkVendedores4;
    private javax.swing.JCheckBox chkVendedores5;
    private javax.swing.JCheckBox chkVendedores6;
    private javax.swing.JCheckBox chkVendores2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    // End of variables declaration//GEN-END:variables
}
